name: CI

on:
  push:
  pull_request:

jobs:
  build-and-run-tests:
    name: Build and run tests
    runs-on: ubuntu-latest
    steps:
      - name: clone-repository
        uses: actions/checkout@v2
      - name: Install dependencties
        run: |
          sudo apt install -y libipc-run-perl
      - name: build-postgres
        run: |
          ./configure --with-icu --enable-cassert --enable-tap-tests
          make -j4
      - name: run-tests
        run: |
          make check-world
      - name: upload-test-summary
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: regression-summary
          path: src/test/regress/regression.out
      - name: upload-test-differences
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: regression-differences
          path: src/test/regress/regression.diffs
